//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summariser.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Summariser.Data.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Ali Kheyrollahi
        ///-- Create date: 2012-07-12
        ///-- Description:	Adds or updates cache entry
        ///-- =============================================
        ///ALTER PROCEDURE Server_AddUpdateCache
        ///	@cacheKeyHash	BINARY(20),
        ///	@routePattern	NVARCHAR(256),
        ///	@resourceUri	NVARCHAR(256),
        ///	@eTag			NVARCHAR(100),
        ///	@lastModified	DATETIME
        ///	 
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AlterProcedure_AddOrUpdateCache {
            get {
                return ResourceManager.GetString("AlterProcedure_AddOrUpdateCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Carl Duguay
        ///-- Create date:	2013-07-10
        ///-- Description:	Removes all CacheKey records
        ///-- =============================================
        ///ALTER PROCEDURE Server_ClearCache	 
        ///AS
        ///BEGIN
        ///	SET NOCOUNT OFF
        ///	DELETE FROM [dbo].[CacheState]
        ///END.
        /// </summary>
        internal static string AlterProcedure_ClearCache {
            get {
                return ResourceManager.GetString("AlterProcedure_ClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Ali Kheyrollahi
        ///-- Create date: 2012-07-12
        ///-- Description:	Deletes a CacheKey record by its id
        ///-- =============================================
        ///ALTER PROCEDURE Server_DeleteCacheById
        ///	@CacheKeyHash BINARY(20) 
        ///AS
        ///BEGIN
        ///	SET NOCOUNT OFF
        ///	DELETE FROM dbo.CacheState WHERE CacheKeyHash = @CacheKeyHash
        ///END.
        /// </summary>
        internal static string AlterProcedure_DeleteCacheById {
            get {
                return ResourceManager.GetString("AlterProcedure_DeleteCacheById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Ali Kheyrollahi
        ///-- Create date: 2013-11-16
        ///-- Description:	Deletes all CacheKey records by its resource uri
        ///-- =============================================
        ///ALTER PROCEDURE Server_DeleteCacheByResourceUri
        ///	@resourceUri NVARCHAR(256) 
        ///AS
        ///BEGIN
        ///	SET NOCOUNT OFF
        ///
        ///	DELETE FROM dbo.CacheState WHERE ResourceUri = @resourceUri
        ///END.
        /// </summary>
        internal static string AlterProcedure_DeleteCacheByResourceUri {
            get {
                return ResourceManager.GetString("AlterProcedure_DeleteCacheByResourceUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Ali Kheyrollahi
        ///-- Create date: 2012-07-12
        ///-- Description:	Deletes all CacheKey records by its route pattern
        ///-- =============================================
        ///ALTER PROCEDURE Server_DeleteCacheByRoutePattern
        ///	@routePattern NVARCHAR(256) 
        ///AS
        ///BEGIN
        ///	SET NOCOUNT OFF
        ///
        ///	DELETE FROM dbo.CacheState WHERE RoutePattern = @routePattern
        ///END.
        /// </summary>
        internal static string AlterProcedure_DeleteCacheByRoutePattern {
            get {
                return ResourceManager.GetString("AlterProcedure_DeleteCacheByRoutePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- =============================================
        ///-- Author:		Ali Kheyrollahi
        ///-- Create date: 2012-07-12
        ///-- Description:	returns cache entry by its Id
        ///-- =============================================
        ///ALTER PROCEDURE Server_GetCache
        ///	@cacheKeyHash		BINARY(20)
        ///	 
        ///AS
        ///BEGIN
        ///	-- SET NOCOUNT ON added to prevent extra result sets from
        ///	-- interfering with SELECT statements.
        ///	SET NOCOUNT ON;
        ///
        ///	SELECT 
        ///		ETag, LastModified
        ///	FROM
        ///		dbo.CacheState
        ///	WHERE
        ///		CacheKeyHash = @cacheKeyHash
        ///
        ///END.
        /// </summary>
        internal static string AlterProcedure_GetCache {
            get {
                return ResourceManager.GetString("AlterProcedure_GetCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////****** Object:  Table [dbo].[CacheState]    Script Date: 07/25/2012 13:38:35 ******/
        ///IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[CacheState]&apos;) AND type in (N&apos;U&apos;))
        ///DROP TABLE [dbo].[CacheState]
        ///
        ///
        ////****** Object:  Table [dbo].[CacheState]    Script Date: 07/25/2012 13:38:35 ******/
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///SET ANSI_PADDING ON
        ///
        ///CREATE TABLE [dbo].[CacheState](
        ///	[CacheKeyHash] [binary](20) NOT NULL,
        ///	[RoutePattern] [nvarchar](256) NOT NULL,
        ///	[Reso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CacheCow_CreateDatabaseAndProcedures {
            get {
                return ResourceManager.GetString("CacheCow_CreateDatabaseAndProcedures", resourceCulture);
            }
        }
    }
}
